name: "Push: prod"

on:
  push:
    branches:    
      - 'prod'

jobs:
  ci:
    uses: ./.github/workflows/call-prod_ci.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/call-deploy_prod.yml
    secrets: inherit
    needs: [ ci ]
